# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScoreRadius < Formula
  desc ""
  homepage "https://score.dev"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/score-spec/score-radius/releases/download/v0.0.6/score-radius_0.0.6_darwin_amd64.tar.gz"
      sha256 "7680a48ce8231139ca455808add3d19c5f6bf517cbef274558abe093721e8f59"

      def install
        bin.install "score-radius"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/score-spec/score-radius/releases/download/v0.0.6/score-radius_0.0.6_darwin_arm64.tar.gz"
      sha256 "8e63fd90b77cc99062d767d2f4991f67b46953a734d6d472dee0b687ff9af631"

      def install
        bin.install "score-radius"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-radius/releases/download/v0.0.6/score-radius_0.0.6_linux_amd64.tar.gz"
      sha256 "292a85b02b2d90ff9c7f4fafbc650de511389dfae79ef1b2916426f5a6ac907e"
      def install
        bin.install "score-radius"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-radius/releases/download/v0.0.6/score-radius_0.0.6_linux_arm64.tar.gz"
      sha256 "af545943c15d0888afa4c7a6108d567e77198538cc765eba06539fc6d8608627"
      def install
        bin.install "score-radius"
      end
    end
  end
end
