# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScoreK8s < Formula
  desc ""
  homepage "https://score.dev"
  version "0.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/score-spec/score-k8s/releases/download/0.10.0/score-k8s_0.10.0_darwin_amd64.tar.gz"
      sha256 "8b960af729db140ee1a8f584c57882a58bbc9d043ba8e2d012f32626f7064078"

      define_method(:install) do
        bin.install "score-k8s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/score-spec/score-k8s/releases/download/0.10.0/score-k8s_0.10.0_darwin_arm64.tar.gz"
      sha256 "00dce9a2ca397772e153f5a7fa17d02447c3095c22667fc8c42a956ff2fd933a"

      define_method(:install) do
        bin.install "score-k8s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-k8s/releases/download/0.10.0/score-k8s_0.10.0_linux_amd64.tar.gz"
      sha256 "ff269a833c3b1f029edf4e599c19e2ea214552c1ac48030728b7aa7bb373b897"
      define_method(:install) do
        bin.install "score-k8s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-k8s/releases/download/0.10.0/score-k8s_0.10.0_linux_arm64.tar.gz"
      sha256 "3703eedb7c4a6b10c3e3be5d50fc80607a3131bb1e0c81a20bee30af81da681e"
      define_method(:install) do
        bin.install "score-k8s"
      end
    end
  end
end
