# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScoreHelm < Formula
  desc ""
  homepage "https://score.dev"
  version "0.10.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/score-spec/score-helm/releases/download/v0.10.5/score-helm_0.10.5_darwin_amd64.tar.gz"
      sha256 "ecb8902fc04740ddb75afe9c3976f79c9148157563d63167bc7a3e4947c90a3e"

      define_method(:install) do
        bin.install "score-helm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/score-spec/score-helm/releases/download/v0.10.5/score-helm_0.10.5_darwin_arm64.tar.gz"
      sha256 "50aef7a01e5c2c8c73c1804b7cfbd9f8e8421f379b335ff938e9ac9c134cf5f7"

      define_method(:install) do
        bin.install "score-helm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-helm/releases/download/v0.10.5/score-helm_0.10.5_linux_amd64.tar.gz"
      sha256 "fb2d8f80a9ad6a100c2fb2b5a51e8d53d588b1d022e63b8341da7ff2bd2435cf"
      define_method(:install) do
        bin.install "score-helm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-helm/releases/download/v0.10.5/score-helm_0.10.5_linux_arm64.tar.gz"
      sha256 "75e2c4a9746118fbab5d2f0ae3328fcef1abf1fefb72bb2422c4674540642977"
      define_method(:install) do
        bin.install "score-helm"
      end
    end
  end
end
