# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScoreCompose < Formula
  desc ""
  homepage "https://score.dev"
  version "0.15.6"

  on_macos do
    on_intel do
      url "https://github.com/score-spec/score-compose/releases/download/0.15.6/score-compose_0.15.6_darwin_amd64.tar.gz"
      sha256 "d7c9300395ee8197d7ede74fc6e1d9fc741a0bc3bbc7aefa8a34299313485063"

      def install
        bin.install "score-compose"
      end
    end
    on_arm do
      url "https://github.com/score-spec/score-compose/releases/download/0.15.6/score-compose_0.15.6_darwin_arm64.tar.gz"
      sha256 "a04cd12a54e85811161433dab12f9d7b56a68acbec986eb067ea9ba3db780f54"

      def install
        bin.install "score-compose"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/score-spec/score-compose/releases/download/0.15.6/score-compose_0.15.6_linux_amd64.tar.gz"
        sha256 "2d09d3468d5b5668f43eb1339f0e8f217bd9089d31981f8d8eec69dff00ebc48"

        def install
          bin.install "score-compose"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/score-spec/score-compose/releases/download/0.15.6/score-compose_0.15.6_linux_arm64.tar.gz"
        sha256 "88975588f75976a4e506e77036d2813401193803b129a045b3f9fae0abf65eaf"

        def install
          bin.install "score-compose"
        end
      end
    end
  end
end
