# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScoreRadius < Formula
  desc ""
  homepage "https://score.dev"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/score-spec/score-radius/releases/download/v0.0.5/score-radius_0.0.5_darwin_amd64.tar.gz"
      sha256 "e834851ed0070543c7eba57af94fa0d398769b04d07c6c8728fcc547a169bd2e"

      def install
        bin.install "score-radius"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/score-spec/score-radius/releases/download/v0.0.5/score-radius_0.0.5_darwin_arm64.tar.gz"
      sha256 "dfbf19666c05859f732ff3e67187b998398da84709be0e2ca0a50038f37ccca3"

      def install
        bin.install "score-radius"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-radius/releases/download/v0.0.5/score-radius_0.0.5_linux_amd64.tar.gz"
      sha256 "a5da30fb9877332a6c04e1925dd189b9572f292c2244768a3d762fbfd4239e35"
      def install
        bin.install "score-radius"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-radius/releases/download/v0.0.5/score-radius_0.0.5_linux_arm64.tar.gz"
      sha256 "f764236b4802b509d39e9b99f6a49eaacd1653bcb967ed8d252a15d03f1deef3"
      def install
        bin.install "score-radius"
      end
    end
  end
end
