# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScoreK8s < Formula
  desc ""
  homepage "https://score.dev"
  version "0.5.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/score-spec/score-k8s/releases/download/0.5.2/score-k8s_0.5.2_darwin_amd64.tar.gz"
      sha256 "dfddd59dbed4dfe4dafcede412ca41c4f3884b6f948481cb259560ef5ac1786b"

      def install
        bin.install "score-k8s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/score-spec/score-k8s/releases/download/0.5.2/score-k8s_0.5.2_darwin_arm64.tar.gz"
      sha256 "3ca3951326c44734b2a67850c523921c5159aad8405dfd0c5d4091d02f281577"

      def install
        bin.install "score-k8s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-k8s/releases/download/0.5.2/score-k8s_0.5.2_linux_amd64.tar.gz"
      sha256 "751fe67e1f5eeebfbebd8d772a84afbc5c3eb8e492d7532b5d2efc383697940a"
      def install
        bin.install "score-k8s"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-k8s/releases/download/0.5.2/score-k8s_0.5.2_linux_arm64.tar.gz"
      sha256 "cfc48343a89dcb57b94e19b448c4128b6989ff5c8ec0cb0c1c9ea539ab4529e3"
      def install
        bin.install "score-k8s"
      end
    end
  end
end
