# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScoreK8s < Formula
  desc ""
  homepage "https://score.dev"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/score-spec/score-k8s/releases/download/0.5.0/score-k8s_0.5.0_darwin_amd64.tar.gz"
      sha256 "72f18764627f714db999bf423f643a82984a4b32c274b735b6c6362caaaed9c4"

      def install
        bin.install "score-k8s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/score-spec/score-k8s/releases/download/0.5.0/score-k8s_0.5.0_darwin_arm64.tar.gz"
      sha256 "4dbd6dfee24db6af66c48cd88f190c2a25d6ebdeda9d2b233c8fe8a74cd70d58"

      def install
        bin.install "score-k8s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-k8s/releases/download/0.5.0/score-k8s_0.5.0_linux_amd64.tar.gz"
      sha256 "376d26ae8949c10ef9da45a7f6750c51f51648b6a53e18f26141bbf340ecee62"
      def install
        bin.install "score-k8s"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-k8s/releases/download/0.5.0/score-k8s_0.5.0_linux_arm64.tar.gz"
      sha256 "b1105585921c75854870ee010834be19fa561ed16b11f7c42f1fcee4e288a8f5"
      def install
        bin.install "score-k8s"
      end
    end
  end
end
