# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScoreCompose < Formula
  desc ""
  homepage "https://score.dev"
  version "0.34.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/score-spec/score-compose/releases/download/0.34.0/score-compose_0.34.0_darwin_amd64.tar.gz"
      sha256 "7801856cfd17e60969ebb790e314ed703b0dd498ef3aac5d734f29b903001bbf"

      define_method(:install) do
        bin.install "score-compose"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/score-spec/score-compose/releases/download/0.34.0/score-compose_0.34.0_darwin_arm64.tar.gz"
      sha256 "968ed2ff09f45acfdd9566f44f892e52d13dd283f95caa1f9b842d264ecaf71c"

      define_method(:install) do
        bin.install "score-compose"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-compose/releases/download/0.34.0/score-compose_0.34.0_linux_amd64.tar.gz"
      sha256 "491a199d616e46c8386db3a3253c1b4070df354efbd81fbec0e2dfd2cfc67ba3"
      define_method(:install) do
        bin.install "score-compose"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-compose/releases/download/0.34.0/score-compose_0.34.0_linux_arm64.tar.gz"
      sha256 "b4b63b7583f87ddb09c6fc61650cd0914868f57669288f27873bc49b89034828"
      define_method(:install) do
        bin.install "score-compose"
      end
    end
  end
end
