# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScoreHumanitec < Formula
  desc ""
  homepage "https://score.dev"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/score-spec/score-humanitec/releases/download/0.5.0/score-humanitec_0.5.0_darwin_amd64.tar.gz"
      sha256 "234f62cf601fa6dc1068b028f622d27cf6b51951cf7dafacaf6d71b415c4df15"

      def install
        bin.install "score-humanitec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/score-spec/score-humanitec/releases/download/0.5.0/score-humanitec_0.5.0_darwin_arm64.tar.gz"
      sha256 "9cc51929776422931d66f22ab2cbb7c2b31972abef56e233bea9eeea066d3817"

      def install
        bin.install "score-humanitec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-humanitec/releases/download/0.5.0/score-humanitec_0.5.0_linux_arm64.tar.gz"
      sha256 "6d1fc8692ce245017148d927f5f981016f9e2ff7baa2294366d2b5328f050e0f"

      def install
        bin.install "score-humanitec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/score-spec/score-humanitec/releases/download/0.5.0/score-humanitec_0.5.0_linux_amd64.tar.gz"
      sha256 "90a3a2346e901de081c872973c5f31dd67c4809cbafba60d37f7715fe1c93463"

      def install
        bin.install "score-humanitec"
      end
    end
  end
end
