# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScoreHumanitec < Formula
  desc ""
  homepage "https://score.dev"
  version "0.10.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/score-spec/score-humanitec/releases/download/0.10.3/score-humanitec_0.10.3_darwin_amd64.tar.gz"
      sha256 "4de1e2aec0fe4cef185cbf0a9935bbc160fba87035a84f1e50b9e99c2fde21e1"

      def install
        bin.install "score-humanitec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/score-spec/score-humanitec/releases/download/0.10.3/score-humanitec_0.10.3_darwin_arm64.tar.gz"
      sha256 "b29d6db1999a5a0096b065f0617ee2282ed7ad958dbe4af5fe7dab789286daf7"

      def install
        bin.install "score-humanitec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/score-spec/score-humanitec/releases/download/0.10.3/score-humanitec_0.10.3_linux_amd64.tar.gz"
      sha256 "423612ab53608cda7dbc05654a320fc0eff3e829ac90e790ed4635f53095b53d"

      def install
        bin.install "score-humanitec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/score-spec/score-humanitec/releases/download/0.10.3/score-humanitec_0.10.3_linux_arm64.tar.gz"
      sha256 "a8f1648f63f4c9a800cd9cf616b8530c40af178e0b6aacf2961aa44c79eaf16e"

      def install
        bin.install "score-humanitec"
      end
    end
  end

  deprecate! date: "2024-05-08", because: "has been replaced by humctl score deploy. For more information visit https://developer.humanitec.com/platform-orchestrator/reference/cli-references/#score-integration."
end
